name: 'GKE Port Forward'
description: Authenticate to GKE
author: Scott Mattan (Rusty)
inputs:
  project_id:
    description: gcp project in which gke cluster resides
    required: true
  cluster_name:
    description: cluster name to which we connect
    required: true
  region:
    description: gcp region in which the gke cluster resides
    required: true
  service_account:
    description: service account used to access gke
    required: true
runs:
  using: "composite"
  steps:
    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.service_account }}
    - uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: ${{ inputs.cluster_name }}
        location: ${{ inputs.region }}
        project_id: ${{ inputs.project_id }}
    - name: Test
      run: 'kubectl get pods'
      shell: bash
