name: 'Setup GKE Connection'
description: Authenticate GCP, Download Kubeconfig and Kubectl 
author: Scott Mattan (Rusty)
branding:
  color: green

inputs:
  project_id:
    description: gcp project in which gke cluster resides
    required: true
  cluster_name:
    description: cluster name to which we connect
    required: true
  region:
    description: gcp region in which the gke cluster resides
    required: true
  service_account:
    description: service account used to access gke
    required: true
  kubeconfig_dir:
    description: directory in which to output kubeconfig
    required: false

runs:
  using: "composite"
  steps:
    
    - name: Authenticate GCP
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ inputs.service_account }}
    
    - name: Work Around Limitations of Next Action
      shell: bash
      run: |
        GITHUB_WORKSPACE_BACKUP="${GITHUB_WORKSPACE}"
        mkdir -p "${GITHUB_WORKSPACE}/tmp"
        export GITHUB_WORKSPACE="${GITHUB_WORKSPACE}/tmp"
    
    - name: Setup KubeConfig
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: ${{ inputs.cluster_name }}
        location: ${{ inputs.region }}
        project_id: ${{ inputs.project_id }}

    - name: Revert Work Around
      shell: bash
      run: export GITHUB_WORKSPACE="${GITHUB_WORKSPACE_BACKUP}"
    
    - name: Setup Kubectl
      shell: bash
      run: |
        BIN_DIR=~/.local/bin/
        KUBECTL_URL="https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        (mkdir -p $BIN_DIR && cd $BIN_DIR && curl -sLO ${KUBECTL_URL})
