name: 'Setup GKE Connection'
description: Authenticate GCP, Download Kubeconfig and Kubectl 
author: Scott Mattan (Rusty)

inputs:
  project_id:
    description: gcp project in which gke cluster resides
    required: true
  cluster_name:
    description: cluster name to which we connect
    required: true
  region:
    description: gcp region in which the gke cluster resides
    required: true
  service_account:
    description: service account used to access gke
    required: true

runs:
  using: "composite"
  steps:
    
    - name: Authenticate GCP
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ inputs.service_account }}
    
    - name: Setup KubeConfig
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: ${{ inputs.cluster_name }}
        location: ${{ inputs.region }}
        project_id: ${{ inputs.project_id }}
    
    - name: Setup Kubectl
      shell: bash
      run: |
        KUSTOMIZE_URL=https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh
        (cd ~/.local/bin/ && curl -s ${KUSTOMIZE_URL} | bash)
        kubectl get pods
