name: 'Setup GKE Connection'
description: Authenticate GCP, Download Kubeconfig and Kubectl 
author: Scott Mattan (Rusty)
branding:
  color: green

inputs:
  project_id:
    description: gcp project in which gke cluster resides
    required: true
  cluster_name:
    description: cluster name to which we connect
    required: true
  region:
    description: gcp region in which the gke cluster resides
    required: true
  service_account:
    description: service account used to access gke
    required: true

runs:
  using: "composite"
  steps:
    - name: Authenticate to GKE
      shell: bash
      run: |
        echo "###################"
        echo "# BEGIN SETUP GCP #"
        echo "###################"

        sudo echo deb '[signed-by=/usr/share/keyrings/gcloud.gpg] https://packages.cloud.google.com/apt cloud-sdk main' \
            >> /etc/apt/sources.list.d/gcloud.list
        sudo curl https://packages.cloud.google.com/apt/doc/apt-key.gpg > /usr/share/keyrings/cloud.google.gpg
        sudo apt update && apt install google-cloud-sdk -y

        mkdir -p ./tmp
        echo "${{ inputs.service_account }}" > ./tmp/key.json
        gcloud auth activate-service-account --key-file=./tmp/key.json
        gcloud container clusters get-credentials "${{ inputs.cluster_name }}" \
            --region="${{ inputs.region }}" \
            --project="${{ inputs.project_id }}"
    
    - name: Setup Kubectl
      shell: bash
      run: |
        BIN_DIR=~/.local/bin/
        KUBECTL_URL="https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        (mkdir -p $BIN_DIR && cd $BIN_DIR && curl -sLO ${KUBECTL_URL})
