name: 'Setup GKE Connection'
description: Authenticate GCP, Download Kubeconfig and Kubectl 
author: Scott Mattan (Rusty)
branding:
  color: green

inputs:
  project_id:
    description: gcp project in which gke cluster resides
    required: true
  cluster_name:
    description: cluster name to which we connect
    required: true
  region:
    description: gcp region in which the gke cluster resides
    required: true
  service_account:
    description: service account used to access gke
    required: true

runs:
  using: "composite"
  steps:
    
    - name: Authenticate GCP
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ inputs.service_account }}
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Setup Kubeconfig
      shell: bash
      run: |
        gcloud container clusters get-credentials "${{ inputs.cluster_name }}" \
            --region="${{ inputs.region }}" \
            --project="${{ inputs.project_id }}"
    
    - name: Setup Kubectl
      shell: bash
      run: |
        BIN_DIR=~/.local/bin/
        KUBECTL_URL="https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        (mkdir -p $BIN_DIR && cd $BIN_DIR && curl -sLO ${KUBECTL_URL})
